
const VITE_APPWRITE_PROJECT_ID="666c1f520024b33450a8"
const VITE_APPWRITE_URL="https://cloud.appwrite.io/v1"
const VITE_APPWRITE_DATABASE_ID="666c83de001002a5e818"
const VITE_APPWRITE_COLLECTION_ID="666c83f8000ded03b49c"
const VITE_APPWRITE_BUCKET_ID="666c85b00030497022cc"
const VITE_TINYMCE_API_KEY ="dkhw118fye7zatiyeh247p8149uj3ztsix8u6dr02rj4as0p"

const conf = {
    APPWRITE_ID: String(VITE_APPWRITE_PROJECT_ID),
    APPWRITE_URL: String(VITE_APPWRITE_URL),
    APPWRITE_DB_ID: String(VITE_APPWRITE_DATABASE_ID),
    APPWRITE_COLLECTION_ID: String(VITE_APPWRITE_COLLECTION_ID),
    APPWRITE_BUCKET_ID: String(VITE_APPWRITE_BUCKET_ID),
    TINYMCE_KEY: String(VITE_TINYMCE_API_KEY)
};

export const {APPWRITE_BUCKET_ID, APPWRITE_COLLECTION_ID, APPWRITE_DB_ID, APPWRITE_ID, APPWRITE_URL, TINYMCE_KEY} = conf